Refine language server test
dotnet/docfx pull request #6909
Opened 2020-12-18 07:28 UTC by yufeih

- Use a higher level semantic
- Enable notification synchronization

2020-12-18 07:42 UTC, 928PJY requested changes
Rebase with the latest v3

2020-12-18 09:10 UTC, VSC-Service-Account commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:16.4467527, 0 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
index 70537eb..1e27524 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
@@ -633277,7 +633277,6 @@ IMPORTANT: This content is for the older Azure AD v1.0 endpoint, use the Microso
         "ShannonLeavitt",
         "gzuber",
         "jborsecnik",
-        "markwolff",
         "ShawnJackson",
         "GitHubber17",
         "TimothyMothra",
@@ -652641,7 +652640,6 @@ IMPORTANT: This content is for the older Azure AD v1.0 endpoint, use the Microso
         "bergano65",
         "bwren",
         "hectorhdzg",
-        "markwolff",
         "MSshujia",
         "nschonni"
       ],
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-functions/functions-monitoring.mta.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-functions/functions-monitoring.mta.json"
index 95d795d..4e6e227 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-functions/functions-monitoring.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-functions/functions-monitoring.mta.json"
@@ -34,7 +34,6 @@
     "ShannonLeavitt",
     "gzuber",
     "jborsecnik",
-    "markwolff",
     "ShawnJackson",
     "GitHubber17",
     "TimothyMothra",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-functions/functions-monitoring.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-functions/functions-monitoring.raw.page.json"
index 0e9f858..e6b51be 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-functions/functions-monitoring.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-functions/functions-monitoring.raw.page.json"
@@ -260,12 +260,6 @@ See the developer guide for your language to learn more about writing logs from
           "display_name": "Graham Zuber",
           "id": "41077832"
         },
-        {
-          "name": "markwolff",
-          "profile_url": "https://github.com/markwolff",
-          "display_name": "Mark Wolff",
-          "id": "5515583"
-        },
         {
           "name": "TimothyMothra",
           "profile_url": "https://github.com/TimothyMothra",
@@ -432,7 +426,6 @@ See the developer guide for your language to learn more about writing logs from
       "ShannonLeavitt",
       "gzuber",
       "jborsecnik",
-      "markwolff",
       "ShawnJackson",
       "GitHubber17",
       "TimothyMothra",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-monitor/app/website-monitoring.mta.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-monitor/app/website-monitoring.mta.json"
index 88bf792..238b345 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-monitor/app/website-monitoring.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-monitor/app/website-monitoring.mta.json"
@@ -18,7 +18,6 @@
     "bergano65",
     "bwren",
     "hectorhdzg",
-    "markwolff",
     "MSshujia",
     "nschonni"
   ],
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-monitor/app/website-monitoring.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-monitor/app/website-monitoring.raw.page.json"
index 3e71ded..d9b4f10 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-monitor/app/website-monitoring.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-monitor/app/website-monitoring.raw.page.json"
@@ -198,12 +198,6 @@ dataset⬇
           "display_name": "Hector Hernandez",
           "id": "39923391"
         },
-        {
-          "name": "markwolff",
-          "profile_url": "https://github.com/markwolff",
-          "display_name": "Mark Wolff",
-          "id": "5515583"
-        },
         {
           "name": "MSshujia",
           "profile_url": "https://github.com/MSshujia",
@@ -240,7 +234,6 @@ dataset⬇
       "bergano65",
       "bwren",
       "hectorhdzg",
-      "markwolff",
       "MSshujia",
       "nschonni"
     ],

```

</details>

2020-12-21 02:50 UTC, 928PJY approved these changes

2020-12-21 02:51 UTC, VSC-Service-Account commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:12.8567939, 0 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
index 67a0c0c..ed81eeb 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
@@ -481717,7 +481717,6 @@ IMPORTANT: This content is for the older Azure AD v1.0 endpoint, use the Microso
         "kraigb",
         "GitHubber17",
         "DCtheGeek",
-        "woehrl01",
         "daveba",
         "arluca",
         "MarkusVi",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.mta.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.mta.json"
index dbe35fe..a5a88d6 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.mta.json"
@@ -15,7 +15,6 @@
     "kraigb",
     "GitHubber17",
     "DCtheGeek",
-    "woehrl01",
     "daveba",
     "arluca",
     "MarkusVi",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.raw.page.json"
index 39d404b..d7b5093 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage-sas.raw.page.json"
@@ -216,12 +216,6 @@ In the following response, the access_token element has been shortened for brevi
           "display_name": "David Coulter",
           "id": "11442954"
         },
-        {
-          "name": "woehrl01",
-          "profile_url": "https://github.com/woehrl01",
-          "display_name": "Lukas Wöhrl",
-          "id": "2535856"
-        },
         {
           "name": "daveba",
           "profile_url": "https://github.com/daveba",
@@ -285,7 +279,6 @@ In the following response, the access_token element has been shortened for brevi
       "kraigb",
       "GitHubber17",
       "DCtheGeek",
-      "woehrl01",
       "daveba",
       "arluca",
       "MarkusVi",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/sectigo-certificate-manager-tutorial.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/sectigo-certificate-manager-tutorial.raw.page.json"
index 699b44d..e70ccf3 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/active-directory/saas-apps/sectigo-certificate-manager-tutorial.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/active-directory/saas-apps/sectigo-certificate-manager-tutorial.raw.page.json"
@@ -254,7 +254,7 @@
         {
           "name": "mmcculligh",
           "profile_url": "https://github.com/mmcculligh",
-          "display_name": "mmcculligh",
+          "display_name": "Murray McCulligh",
           "id": "5527796"
         },
         {
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/load-balancer/quickstart-load-balancer-standard-public-portal.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/load-balancer/quickstart-load-balancer-standard-public-portal.raw.page.json"
index 0f73c18..3da8904 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/load-balancer/quickstart-load-balancer-standard-public-portal.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/load-balancer/quickstart-load-balancer-standard-public-portal.raw.page.json"
@@ -1294,7 +1294,7 @@
         {
           "name": "stpanigr",
           "profile_url": "https://github.com/stpanigr",
-          "display_name": "stpanigr",
+          "display_name": "Stithi",
           "id": "44934655"
         }
       ],

```

</details>

2020-12-21 02:56 UTC, VSC-Service-Account commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/sql-docs-pr'>sql-docs-pr</a>(00:00:47.4576848, 0 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/.publish.json" "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/.publish.json"
index afc86e5..e225415 100644
--- "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/.publish.json"
@@ -171044,7 +171044,6 @@
         "MightyPen",
         "rothja",
         "Duncan-Howe",
-        "glensmall",
         "stevestein",
         "Saisang",
         "craigg-msft",
diff --git "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.mta.json" "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.mta.json"
index 30b12d9..7602a39 100644
--- "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.mta.json"
@@ -20,7 +20,6 @@
     "MightyPen",
     "rothja",
     "Duncan-Howe",
-    "glensmall",
     "stevestein",
     "Saisang",
     "craigg-msft",
diff --git "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.raw.page.json" "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.raw.page.json"
index 4f3afa1..09bfa9b 100644
--- "a/D:/docfx.TestData\\regression-test.sql-docs-pr\\output/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.sql-docs-pr\\.temp/docs/sql/12410a43/linux/tutorial-sql-server-containers-kubernetes.raw.page.json"
@@ -342,12 +342,6 @@ spec:⬇
           "display_name": "Duncan-Howe",
           "id": "2671343"
         },
-        {
-          "name": "glensmall",
-          "profile_url": "https://github.com/glensmall",
-          "display_name": "Glen Small",
-          "id": "14293295"
-        },
         {
           "name": "stevestein",
           "profile_url": "https://github.com/stevestein",
@@ -416,7 +410,6 @@ spec:⬇
       "MightyPen",
       "rothja",
       "Duncan-Howe",
-      "glensmall",
       "stevestein",
       "Saisang",
       "craigg-msft",

```

</details>

2020-12-21 02:57 UTC, VSC-Service-Account commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/windowsserverdocs-pr'>windowsserverdocs-pr</a>(00:00:09.3614438, 0 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/azure-site-recovery-services-integration.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/azure-site-recovery-services-integration.raw.page.json"
index eca54fd..79a295c 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/azure-site-recovery-services-integration.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/azure-site-recovery-services-integration.raw.page.json"
@@ -90,7 +90,7 @@
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "nnamuhcs",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/azure-virtual-network-integration.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/azure-virtual-network-integration.raw.page.json"
index 8980754..27d76f6 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/azure-virtual-network-integration.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/azure-virtual-network-integration.raw.page.json"
@@ -92,7 +92,7 @@ Completing the configuration of an Azure Virtual network in the cloud can take a
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "nnamuhcs",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/get-started.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/get-started.raw.page.json"
index e06583d..7c1d141 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/get-started.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/get-started.raw.page.json"
@@ -93,7 +93,7 @@
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "nnamuhcs",
@@ -134,7 +134,7 @@
     "pdf_url_template": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}{pdfName}",
     "_op_ogTitle": "Get started with Windows Server Essentials",
     "_op_og_attr_encoded_description": "Learn about Windows Server Essentials edition which is a cloud-connected first server designed for small businesses with up to 25 users and 50 devices.",
-    "_op_article_date_quotedISO8601": "\"2020-12-21T01:20:31.706Z\"",
+    "_op_article_date_quotedISO8601": "\"2020-12-21T01:20:31.709Z\"",
     "_op_article_date_display": "12/21/2020",
     "_op_article_date_source": "git",
     "word_count": 236,
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/release-notes.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/release-notes.raw.page.json"
index 61e0e57..7c6e1e2 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/release-notes.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/release-notes.raw.page.json"
@@ -49,7 +49,7 @@
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "nnamuhcs",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/support-for-larger-deployments.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/support-for-larger-deployments.raw.page.json"
index c7dd8dd..3addc1c 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/get-started/support-for-larger-deployments.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/get-started/support-for-larger-deployments.raw.page.json"
@@ -80,7 +80,7 @@
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "nnamuhcs",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/install/create-a-server-recovery-dvd-for-multi-language-support.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/install/create-a-server-recovery-dvd-for-multi-language-support.raw.page.json"
index 47fd572..5447e78 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/install/create-a-server-recovery-dvd-for-multi-language-support.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/install/create-a-server-recovery-dvd-for-multi-language-support.raw.page.json"
@@ -139,7 +139,7 @@ Dism /Image:C:\\InstallMount /ScratchDir:C:\\temp_Scratch /Add-Package /PackageP
         }
       ],
       "update_at": "12/21/2020",
-      "updated_at_date_time": "2020-12-21T01:20:31.706Z"
+      "updated_at_date_time": "2020-12-21T01:20:31.709Z"
     },
     "_op_pdfUrlPrefixTemplate": "https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerEssentialsDocs-pr/{branchName}",
     "author": "daveba",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/migrate/migrate-server-data-to-windows-server-essentials.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/EssentialsDocs/windows-server-essentials/migrate/migrate-server-data-to-windows-server-essentials.raw.page.json"
index 91c4708..5ecd063 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/EssentialsDocs/windows-server-essentials/migrate/migrate-server-data-to-windows-server-essentials.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/E [...]

2020-12-21 02:59 UTC, yufeih commented on src/docfx/serve/LanguageServerBuilder.cs
> +            _buildChannel.Writer.TryWrite(false);
reverted

2020-12-21 03:00 UTC, merged