change UidNotFound error level
dotnet/docfx pull request #7749
Opened 2021-12-09 08:33 UTC by fkpwolf

AB#530134

"due to the decentralized nature of how content and certifications get created, could we just add a warning"
https://dev.azure.com/ceapex/Engineering/_boards/board/t/Docs%20Content%20Hosting%20and%20Storage%20Team/Stories/?workitem=328267#8939105

And I also move UidNotFound to Link category since it has no property path so Validation Build rules can't override on it (propertyPath is mandatory input in Rule edit form).

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/azure-devops-docs-pr'>azure-devops-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.azure-devops-docs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/Azure/azure-docs-rest-apis'>azure-docs-rest-apis</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.azure-docs-rest-apis' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress --prune azure-docs-pr' failed in directory 'D:/docfx.TestData\regression-test.azure-docs-pr' with exit code 128, message: 
 fatal: Cannot prompt because user interactivity has been disabled.
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Username for 'https://dev.azure.com/ceapex/Engineering/_git/docfx.TestData': terminal prompts disabled

   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__1() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 197
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 197
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/azure-docs-cli'>azure-docs-cli</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.azure-docs-cli' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/dataprep-dotnet-pr'>dataprep-dotnet-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.dataprep-dotnet-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/azure-mediaplayer-typescript'>azure-mediaplayer-typescript</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.azure-mediaplayer-typescript' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/dotnet/docs'>docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:46 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/DevSandbox'>DevSandbox</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.DevSandbox' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:48 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/dynamics365-docs-odata-apis'>dynamics365-docs-odata-apis</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.dynamics365-docs-odata-apis' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:48 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/windowsserverdocs-pr'>windowsserverdocs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.windowsserverdocs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/DocsRoot'>DocsRoot</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.DocsRoot' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/dynamics365smb-devitpro'>dynamics365smb-devitpro</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.dynamics365smb-devitpro' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/dotnet/EntityFramework.ApiDocs'>EntityFramework.ApiDocs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.EntityFramework.ApiDocs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/bot-docs-pr'>dryrun.bot-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.dryrun.bot-docs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/test'>htmlTest.test</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.htmlTest.test' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:49 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>dryrun.azure-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.dryrun.azure-docs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/dotnet/AspNetCore.Docs'>htmlTest.AspNetCore.Docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.htmlTest.AspNetCore.Docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/powerbi-docs-pr.de-DE'>powerbi-docs-pr.de-DE</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.powerbi-docs-pr.de-DE' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/microsoft-365-docs-pr.zh-CN'>microsoft-365-docs-pr.zh-CN</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress --prune microsoft-365-docs-pr.zh-CN' failed in directory 'D:/docfx.TestData\regression-test.microsoft-365-docs-pr.zh-CN' with exit code 128, message: 
 fatal: Cannot prompt because user interactivity has been disabled.
fatal: Cannot prompt because user interactivity has been disabled.
fatal: could not read Username for 'https://dev.azure.com/ceapex/Engineering/_git/docfx.TestData': terminal prompts disabled

   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__1() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 197
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 197
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/learn-pr'>learn-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.learn-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/mc-docs-pr'>mc-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.mc-docs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:51 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/microsoftgraph/microsoft-graph-docs'>microsoft-graph-docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.microsoft-graph-docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:52 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/PowerShell-Docs'>PowerShell-Docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.PowerShell-Docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:52 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/quantum-docs-private'>quantum-docs-private</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.quantum-docs-private' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:53 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/dotnet/roslyn-api-docs'>roslyn-api-docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.roslyn-api-docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:53 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/VBA-Docs'>VBA-Docs</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.VBA-Docs' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:54 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/sql-docs-pr'>sql-docs-pr</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.sql-docs-pr' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:54 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://github.com/MicrosoftDocs/test'>test</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.test' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 08:54 UTC, opbld41 commented
<details><summary>🚗🌳💥🤕🚑<a href='https://dev.azure.com/cpubwin/windows-compatibility/_git/windows-compatibility'>windows-compatibility</a>(00:00:00)</summary>

```
System.InvalidOperationException: '"git" *** fetch origin --progress template' failed in directory 'D:/docfx.TestData\regression-test.windows-compatibility' with exit code 128, message: 
 
   at Microsoft.Docs.Build.RegressionTest.Exec(String fileName, String arguments, String stdin, String cwd, Dictionary`2 env, Boolean ignoreError, Boolean redirectStandardError, Int32[] allowExitCodes, String[] secrets) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 408
   at Microsoft.Docs.Build.RegressionTest.<>c__DisplayClass16_0.<EnsureTestData>b__0() in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Docs.Build.RegressionTest.Retry(Func`1 action, Int32 retryCount) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 521
   at Microsoft.Docs.Build.RegressionTest.EnsureTestData(Options opts, String workingFolder) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 192
   at Microsoft.Docs.Build.RegressionTest.Run(Options opts) in D:\a\_work\1\s\test\docfx.RegressionTest\RegressionTest.cs:line 56

```

</details>

2021-12-09 09:09 UTC, yufeih approved these changes

2021-12-09 09:09 UTC, yufeih commented
@mingwli The regression test cases all failed

2021-12-09 09:24 UTC, mingwli commented
> @mingwli The regression test cases all failed

AB#518489

2021-12-09 11:45 UTC, herohua commented
adding several people to review this change

2021-12-09 12:01 UTC, herohua commented on src/docfx/Errors.cs
> +        public static Error UidNotFound(string uid, IEnumerable<string?> repositories, string? schemaType)
Would it be a better name of `ExternalUidNotFound`?

2021-12-09 12:02 UTC, herohua commented on src/docfx/Errors.cs
> -        public static Error UidNotFound(string uid, IEnumerable<string?> repositories, string? schemaType)
I'd prefer keep it in class `Xref`

2021-12-09 12:05 UTC, herohua requested changes
This change seems will break learning path/module check - is this by design?
https://dev.azure.com/ceapex/Engineering/_git/docs-ui?path=/packages/schemas/src/LearningPath.schema.json&version=GBdevelop&line=135&lineEnd=136&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

2021-12-10 10:13 UTC, herohua commented
/azp run

2021-12-10 10:51 UTC, opbld41 commented
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>azure-docs-pr</a>(00:01:49.3451748 | exceed 100s, 1150 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
index e21d36d..a5fa3a9 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/.publish.json"
@@ -834068,7 +834068,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-10-19 12:32 AM",
-      "word_count": 4326
+      "word_count": 4328
     },
     {
       "url": "/azure/azure-sql/database/features-comparison",
@@ -838889,7 +838889,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-10-19 12:32 AM",
-      "word_count": 402
+      "word_count": 404
     },
     {
       "url": "/azure/azure-sql/database/scripts/add-database-to-failover-group-powershell",
@@ -839144,7 +839144,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-12-02 12:35 AM",
-      "word_count": 340
+      "word_count": 347
     },
     {
       "url": "/azure/azure-sql/database/scripts/create-and-configure-database-powershell",
@@ -839298,7 +839298,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 367
+      "word_count": 369
     },
     {
       "url": "/azure/azure-sql/database/scripts/monitor-and-scale-database-powershell",
@@ -839451,7 +839451,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 365
+      "word_count": 367
     },
     {
       "url": "/azure/azure-sql/database/scripts/move-database-between-elastic-pools-powershell",
@@ -839603,7 +839603,7 @@ Azure SQL Database</p>⬇
       "toc_rel": "../../toc.json",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 327
+      "word_count": 329
     },
     {
       "url": "/azure/azure-sql/database/scripts/setup-geodr-and-failover-database-powershell",
@@ -1364991,7 +1364991,7 @@ Azure Synapse Analytics</p>⬇
       "title": "CLI example- Failover group - Azure SQL Database elastic pool - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-10-26 12:33 AM",
-      "word_count": 481
+      "word_count": 483
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-add-managed-instance-to-failover-group-cli",
@@ -1365039,7 +1365039,7 @@ Azure Synapse Analytics</p>⬇
       "title": "CLI example- Failover group - Azure SQL Managed Instance - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-10-26 12:33 AM",
-      "word_count": 1244
+      "word_count": 1315
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-auditing-and-threat-detection-cli",
@@ -1365136,7 +1365136,7 @@ Azure Synapse Analytics</p>⬇
       "title": "Azure CLI: Backup a database in Azure SQL Database - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 357
+      "word_count": 359
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-copy-database-to-new-server-cli",
@@ -1365234,7 +1365234,7 @@ Azure Synapse Analytics</p>⬇
       "title": "Azure CLI: Create a managed instance - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 646
+      "word_count": 671
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-create-managed-instance-to-failover-group-cli",
@@ -1365285,7 +1365285,7 @@ Azure Synapse Analytics</p>⬇
       "title": "Azure CLI: Add managed instance to failover group - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-10-26 12:33 AM",
-      "word_count": 1252
+      "word_count": 1323
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-import-from-bacpac-cli",
@@ -1365335,7 +1365335,7 @@ Azure Synapse Analytics</p>⬇
       "title": "Azure CLI: Import BACPAC file to database in Azure SQL Database - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 379
+      "word_count": 383
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-import-purview-labels",
@@ -1365431,7 +1365431,7 @@ Azure Synapse Analytics</p>⬇
       "title": "Azure CLI: Restore a backup - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 342
+      "word_count": 370
     },
     {
       "url": "/azure/sql-database/scripts/sql-database-setup-geodr-and-failover-database-cli",
@@ -1365621,7 +1365621,7 @@ Azure Synapse Analytics</p>⬇
       "title": "CLI example- Enable BYOK TDE - Azure SQL Managed Instance - Azure SQL Database | Microsoft Docs",
       "uhfHeaderId": "azure",
       "updated_at": "2021-08-03 09:47 AM",
-      "word_count": 434
+      "word_count": 468
     },
     {
       "url": "/azure/sql-server-stretch-database/",
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-sql/database/failover-group-add-single-database-tutorial.mta.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-sql/database/failover-group-add-single-database-tutorial.mta.json"
index c302414..6c5cdfd 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-sql/database/failover-group-add-single-database-tutorial.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-sql/database/failover-group-add-single-database-tutorial.mta.json"
@@ -44,5 +44,5 @@
   "toc_rel": "../toc.json",
   "uhfHeaderId": "azure",
   "updated_at": "2021-10-19 12:32 AM",
-  "word_count": 4326
+  "word_count": 4328
 }
\ No newline at end of file
diff --git "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-sql/database/failover-group-add-single-database-tutorial.raw.page.json" "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-sql/database/failover-group-add-single-database-tutorial.raw.page.json"
index f0d3592..38d552a 100644
--- "a/D:/docfx.TestData\\regression-test.azure-docs-pr\\output/azure/azure-sql/database/failover-group-add-single-database-tutorial.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.azure-docs-pr\\.temp/azure/azure-sql/database/failover-group-add-single-database-tutorial.raw.page.json"
@@ -885,16 +885,16 @@ Write-host &quot;Failover group name is&quot; $failoverGroupName⬇
 let randomIdentifier=$RANDOM*$RANDOM⬇
 location=&quot;East US&quot;⬇
 resourceGroup=&quot;msdocs-azuresql-rg-$randomIdentifier&quot;⬇
-tag=&quot;add-single-db-to-failover-group-az-cli.sh&quot;⬇
+tag=&quot;add-single-db-to-failover-group-az-cli&quot;⬇
 server=&quot;msdocs-azuresql-server-$randomIdentifier&quot;⬇
-database=&quot;msdocs-azuresql-db-$randomIdentifier&quot;⬇
+database=&quot;msdocsazuresqldb$randomIdentifier&quot;⬇
 login=&quot;msdocsAdminUser&quot;⬇
 password=&quot;Pa$$w0rD-$randomIdentifier&quot;⬇
 failoverGroup=&quot;msdocs-azuresql-failover-group-$randomIdentifier&quot;⬇
 failoverLocation=&quot;Central US&quot;⬇
 failoverServer=&quot;msdocs-azuresql-failover-server-$randomIdentifier&quot;⬇
 echo &quot;Using resource group $resourceGroup with login: $login, password: $password...&quot;⬇
-echo &quot;Creating $resource...&quot;⬇
+echo &quot;Creating $resource in $location...&quot;⬇
 az group create --name $resourceGroup --location &quot [...]

2021-12-10 10:51 UTC, opbld41 commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/DevSandbox'>DevSandbox</a>(00:00:05.5418717)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/.dependencymap.json" "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/.dependencymap.json"
index 2953b65..c3398df 100644
--- "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/.dependencymap.json"
+++ "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/.dependencymap.json"
@@ -697,37 +697,13 @@
         "source": "reference/windows.devices.bluetooth.bluetoothadapter.yml",
         "type": "file"
       },
-      {
-        "source": "tutorial/azurecli.yml",
-        "type": "file"
-      },
-      {
-        "source": "tutorial/azurepowershell.yml",
-        "type": "file"
-      },
       {
         "source": "tutorial/hello-world.yml",
         "type": "file"
       },
-      {
-        "source": "tutorial/interpolated-strings.yml",
-        "type": "file"
-      },
-      {
-        "source": "tutorial/lab.yml",
-        "type": "file"
-      },
       {
         "source": "tutorial/numbers-in-csharp.yml",
         "type": "file"
-      },
-      {
-        "source": "tutorial/rest.yml",
-        "type": "file"
-      },
-      {
-        "source": "tutorial/video.yml",
-        "type": "file"
       }
     ],
     "translation/index.md": [
diff --git "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/full-dependent-list.txt" "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/full-dependent-list.txt"
index 7a09a98..7fd024e 100644
--- "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/full-dependent-list.txt"
+++ "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/full-dependent-list.txt"
@@ -603,46 +603,16 @@
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\reference\\windows.devices.bluetooth.bluetoothadapter.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\azurecli.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\azurepowershell.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\hello-world.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\interpolated-strings.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\lab.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\numbers-in-csharp.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\rest.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\video.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\translation\\index.md",
diff --git "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/server-side-dependent-list.txt" "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/server-side-dependent-list.txt"
index 7a09a98..7fd024e 100644
--- "a/D:/docfx.TestData\\regression-test.DevSandbox\\output/devsandbox/server-side-dependent-list.txt"
+++ "b/D:/docfx.TestData\\regression-test.DevSandbox\\.temp/devsandbox/server-side-dependent-list.txt"
@@ -603,46 +603,16 @@
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\reference\\windows.devices.bluetooth.bluetoothadapter.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\azurecli.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\azurepowershell.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\hello-world.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\interpolated-strings.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\lab.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
   "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\numbers-in-csharp.yml"
 }
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\rest.yml"
-}
-{
-  "dependency_type": "file",
-  "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\toc.yml",
-  "to_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\tutorial\\video.yml"
-}
 {
   "dependency_type": "file",
   "from_file_path": "D:\\docfx.TestData\\regression-test.DevSandbox\\DevSandbox\\devsandbox\\translation\\index.md",


```

</details>

2021-12-10 10:55 UTC, opbld41 commented
<details><summary>🧭<a href='https://github.com/dotnet/AspNetCore.Docs'>htmlTest.AspNetCore.Docs</a>(00:00:30.1003654 | exceed 30s)</summary>

```csharp
 58% | docfx!Microsoft.Docs.Build.TocLoader+<>c__DisplayClass22_0.<LoadTocNodes>b__0(int32)
 55% | docfx!Microsoft.Docs.Build.TocLoader.LoadTocNode(value class Microsoft.Docs.Build.SourceInfo`1<class Microsoft.Docs.Build.TocNode>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.FilePath>,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.FilePath>)
 36% | docfx!Microsoft.Docs.Build.TocLoader.LoadTocNodes(class System.Collections.Generic.List`1<value class Microsoft.Docs.Build.SourceInfo`1<class Microsoft.Docs.Build.TocNode>>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.FilePath>,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.FilePath>)
 17% | docfx!Microsoft.Docs.Build.TocLoader.ProcessTopicItem(class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.FilePath>,value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,bool)
 15% | docfx!Microsoft.Docs.Build.XrefResolver.ResolveXrefByUid(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,value class System.Nullable`1<value class Microsoft.Docs.Build.MonikerList>)
 13% | docfx!Microsoft.Docs.Build.XrefResolver.ResolveXrefSpec(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,value class System.Nullable`1<value class Microsoft.Docs.Build.MonikerList>)
 11% | docfx!Microsoft.Docs.Build.XrefResolver.Resolve(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,value class System.Nullable`1<value class Microsoft.Docs.Build.MonikerList>)
  8% | docfx!Microsoft.Docs.Build.XrefResolver.ResolveInternalXrefSpec(class System.String,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,value class System.Nullable`1<value class Microsoft.Docs.Build.MonikerList>)
  8% | docfx!Microsoft.Docs.Build.Watch`1[System.__Canon].get_Value()
  6% | docfx!Microsoft.Docs.Build.ParallelUtility+<>c__DisplayClass2_0`1[System.__Canon].<ForEach>b__0(!0)
  5% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass6_0.<CreateCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  5% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass4_0.<BuildCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  5% | docfx!Microsoft.Docs.Build.Builder.Run(class Microsoft.Docs.Build.CommandLineOptions,class Microsoft.Docs.Build.Package)
  5% | docfx!Microsoft.Docs.Build.Builder.Build(class Microsoft.Docs.Build.ErrorBuilder,class System.IProgress`1<class System.String>,class System.String[])
  4% | docfx!Microsoft.Docs.Build.ParallelUtility.ForEach(class Microsoft.Docs.Build.LogScope,class Microsoft.Docs.Build.ErrorBuilder,class System.Collections.Generic.IEnumerable`1<!!0>,class System.Action`1<!!0>)
  3% | docfx!Microsoft.Docs.Build.Builder+<>c__DisplayClass8_0.<Build>b__0(class Microsoft.Docs.Build.DocsetBuilder)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.Build(class System.String[])
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder+<>c__DisplayClass42_1.<Build>b__16(class Microsoft.Docs.Build.FilePath)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.BuildFile(class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.ContentValidator,class Microsoft.Docs.Build.ResourceBuilder,class Microsoft.Docs.Build.PageBuilder,class Microsoft.Docs.Build.TocBuilder,class Microsoft.Docs.Build.RedirectionBuilder)
  3% | docfx!Microsoft.Docs.Build.PageBuilder.Build(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.GetFilesToBuild(class System.String[])
  3% | docfx!Microsoft.Docs.Build.TocMap.GetFiles()
  3% | docfx!Microsoft.Docs.Build.Watch`1[System.ValueTuple`3[System.__Canon,System.__Canon,System.__Canon]].get_Value()
  3% | docfx!Microsoft.Docs.Build.TocMap.BuildTocMap()
  2% | docfx!Microsoft.Docs.Build.PageBuilder.LoadMarkdown(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
  2% | docfx!Microsoft.Docs.Build.MarkdownEngine.ToHtml(class Microsoft.Docs.Build.ErrorBuilder,class System.String,class Microsoft.Docs.Build.SourceInfo,value class Microsoft.Docs.Build.MarkdownPipelineType,class Microsoft.Docs.Build.ConceptualModel,bool)
  2% | Markdig!Markdig.Markdown.ToHtml(class System.String,class Markdig.MarkdownPipeline)
  2% | Microsoft.Docs.MarkdigExtensions!Microsoft.Docs.MarkdigExtensions.ResolveLinkExtension.UpdateLinks(class Markdig.Syntax.MarkdownObject)
  2% | docfx!Microsoft.Docs.Build.MarkdigUtility.<Replace>g__ReplaceCore|7_0(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,class Markdig.Syntax.MarkdownObject>)
  2% | docfx!Microsoft.Docs.Build.TocMap+<>c__DisplayClass17_0.<BuildTocMap>b__1(class Microsoft.Docs.Build.FilePath)

```

</details>

2021-12-10 10:56 UTC, opbld41 commented
<details><summary>⚠<a href='https://github.com/dotnet/docs'>docs</a>(00:00:45.2153390)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.docs\\output/.publish.json" "b/D:/docfx.TestData\\regression-test.docs\\.temp/.publish.json"
index 6296032..00ebe2e 100644
--- "a/D:/docfx.TestData\\regression-test.docs\\output/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.docs\\.temp/.publish.json"
@@ -92724,7 +92724,7 @@
       "github_contributors": [
         "BillWagner",
         "pkulikov",
-        "sampreeth1999"
+        "sampreeth-inkulu"
       ],
       "helpviewer_keywords": [
         "default [C#]",
diff --git "a/D:/docfx.TestData\\regression-test.docs\\output/dotnet/csharp/language-reference/builtin-types/default-values.mta.json" "b/D:/docfx.TestData\\regression-test.docs\\.temp/dotnet/csharp/language-reference/builtin-types/default-values.mta.json"
index 877f65c..818e479 100644
--- "a/D:/docfx.TestData\\regression-test.docs\\output/dotnet/csharp/language-reference/builtin-types/default-values.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.docs\\.temp/dotnet/csharp/language-reference/builtin-types/default-values.mta.json"
@@ -15,7 +15,7 @@
   "github_contributors": [
     "BillWagner",
     "pkulikov",
-    "sampreeth1999"
+    "sampreeth-inkulu"
   ],
   "helpviewer_keywords": [
     "default [C#]",
diff --git "a/D:/docfx.TestData\\regression-test.docs\\output/dotnet/csharp/language-reference/builtin-types/default-values.raw.page.json" "b/D:/docfx.TestData\\regression-test.docs\\.temp/dotnet/csharp/language-reference/builtin-types/default-values.raw.page.json"
index a31720c..4e65948 100644
--- "a/D:/docfx.TestData\\regression-test.docs\\output/dotnet/csharp/language-reference/builtin-types/default-values.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.docs\\.temp/dotnet/csharp/language-reference/builtin-types/default-values.raw.page.json"
@@ -92,9 +92,9 @@ Console.WriteLine(n);  // output: (0, 0)⬇
           "id": "15279990"
         },
         {
-          "name": "sampreeth1999",
-          "profile_url": "https://github.com/sampreeth1999",
-          "display_name": "sampreeth1999",
+          "name": "sampreeth-inkulu",
+          "profile_url": "https://github.com/sampreeth-inkulu",
+          "display_name": "Sampreeth Inkulu",
           "id": "32814049"
         }
       ],
@@ -118,7 +118,7 @@ Console.WriteLine(n);  // output: (0, 0)⬇
     "github_contributors": [
       "BillWagner",
       "pkulikov",
-      "sampreeth1999"
+      "sampreeth-inkulu"
     ],
     "helpviewer_keywords": [
       "default [C#]",


```

</details>

2021-12-10 10:59 UTC, opbld41 commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/test'>test</a>(00:00:17.6041357, 997 more diff)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.test\\output/test/.links.json" "b/D:/docfx.TestData\\regression-test.test\\.temp/test/.links.json"
index 7487e0e..da841fa 100644
--- "a/D:/docfx.TestData\\regression-test.test\\output/test/.links.json"
+++ "b/D:/docfx.TestData\\regression-test.test\\.temp/test/.links.json"
@@ -57683,30 +57683,6 @@
       "source_git_url": "https://github.com/MicrosoftDocs/test/blob/master/test/docfx.json",
       "source_line": 52
     },
-    {
-      "source_url": "/test/powershell/az.compute/add-azcontainerserviceagentpoolprofile",
-      "target_url": "https://review.docs.microsoft.com/dotnet/api/microsoft.azure.commands.common.authentication.abstractions.core.iazurecontextcontainer?branch=master",
-      "source_git_url": "https://github.com/MicrosoftDocs/test/blob/master/test/powershell/Az.Compute/Add-AzContainerServiceAgentPoolProfile.yml",
-      "source_line": 69
-    },
-    {
-      "source_url": "/test/powershell/az.compute/add-azcontainerserviceagentpoolprofile",
-      "target_url": "https://review.docs.microsoft.com/dotnet/api/microsoft.azure.commands.compute.automation.models.pscontainerservice?branch=master",
-      "source_git_url": "https://github.com/MicrosoftDocs/test/blob/master/test/powershell/Az.Compute/Add-AzContainerServiceAgentPoolProfile.yml",
-      "source_line": 7
-    },
-    {
-      "source_url": "/test/powershell/az.compute/add-azcontainerserviceagentpoolprofile",
-      "target_url": "https://review.docs.microsoft.com/dotnet/api/microsoft.azure.commands.compute.automation.models.pscontainerservice?branch=master",
-      "source_git_url": "https://github.com/MicrosoftDocs/test/blob/master/test/powershell/Az.Compute/Add-AzContainerServiceAgentPoolProfile.yml",
-      "source_line": 14
-    },
-    {
-      "source_url": "/test/powershell/az.compute/add-azcontainerserviceagentpoolprofile",
-      "target_url": "https://review.docs.microsoft.com/dotnet/api/microsoft.azure.commands.compute.automation.models.pscontainerservice?branch=master",
-      "source_git_url": "https://github.com/MicrosoftDocs/test/blob/master/test/powershell/Az.Compute/Add-AzContainerServiceAgentPoolProfile.yml",
-      "source_line": 45
-    },
     {
       "source_url": "/test/powershell/az.compute/add-azcontainerserviceagentpoolprofile",
       "target_url": "https://review.docs.microsoft.com/dotnet/api/system.int32?branch=main",
diff --git "a/D:/docfx.TestData\\regression-test.test\\output/test/test/docs/hub/azure-edit-link.raw.page.json" "b/D:/docfx.TestData\\regression-test.test\\.temp/test/test/docs/hub/azure-edit-link.raw.page.json"
index 3a48b4c..e7cd5ba 100644
--- "a/D:/docfx.TestData\\regression-test.test\\output/test/test/docs/hub/azure-edit-link.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.test\\.temp/test/test/docs/hub/azure-edit-link.raw.page.json"
@@ -87,7 +87,7 @@
 \t\t\t\t\t\t\t<button data-facet=\"all\" class=\"all-facet button has-inner-focus justify-content-space-between button-clear button-sm font-weight-semibold button-block justify-content-\">All</button>⬇
 \t\t\t\t\t\t</li>⬇
 \t\t\t\t\t\t<li class=\"is-unstyled border-bottom has-padding-bottom-extra-small has-margin-bottom-extra-small\">⬇
-\t\t\t\t\t\t\t<button data-facet=\"featured\" class=\"featured-facet hub-facet button has-inner-focus justify-content-space-between button-clear button-sm font-weight-semibold button-block justify-content-\">Featured</button>⬇
+\t\t\t\t\t\t\t<button data-facet=\"popular\" class=\"featured-facet hub-facet button has-inner-focus justify-content-space-between button-clear button-sm font-weight-semibold button-block justify-content-\">Popular</button>⬇
 \t\t\t\t\t\t</li>⬇
 \t\t\t\t\t\t<li class=\"is-unstyled\">⬇
 \t\t\t\t\t\t\t<button data-facet=\"ai-machine-learning\" class=\"hub-facet button has-inner-focus justify-content-space-between button-clear button-sm font-weight-semibold button-block justify-content-\">AI + Machine Learning</button>⬇
@@ -167,7 +167,7 @@
 \t\t\t\t<div id=\"category-navigation-mobile\" class=\"dropdown-menu button-block padding-xs font-size-sm has-body-background-medium\" role=\"menu\">⬇
 \t\t\t\t\t<ul class=\"margin-none\">⬇
 \t\t\t\t\t\t\t<li class=\"is-unstyled border-bottom has-padding-bottom-extra-small has-margin-bottom-extra-small\">⬇
-\t\t\t\t\t\t\t\t<button class=\"hub-facet dropdown-menu-close button button-block justify-content-space-between button-clear button-sm font-weight-semibold has-inner-focus\">Featured</button>⬇
+\t\t\t\t\t\t\t\t<button class=\"hub-facet dropdown-menu-close button button-block justify-content-space-between button-clear button-sm font-weight-semibold has-inner-focus\">Popular</button>⬇
 \t\t\t\t\t\t\t</li>⬇
 \t\t\t\t\t\t\t<li class=\"is-unstyled\">⬇
 \t\t\t\t\t\t\t\t<button data-facet=\"ai-machine-learning\" class=\"hub-facet dropdown-menu-close button button-block justify-content-space-between button-clear button-sm font-weight-semibold has-inner-focus\">AI + Machine Learning</button>⬇
@@ -284,7 +284,7 @@
 \t\t\t\t\t\t\t\t<h3 class=\"font-size-h6 margin-none\">App Configuration</h3>⬇
 \t\t\t\t\t\t\t</a>⬇
 \t\t\t\t</div>⬇
-\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Featured Compute Mobile Web \">⬇
+\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Popular Compute Mobile Web \">⬇
 \t\t\t\t\t\t<div class=\"is-hidden-mobile box position-relative margin-none is-full-height has-heavy-shadow-hover border-high-contrast-hover has-padding-large text-decoration-none\" aria-labelledby=\"app-service-57\">⬇
 \t\t\t\t\t\t\t\t<img src=\"https://static.docs.com/ui/media/product/azure/app-service.svg\" alt=\"\" loading=\"lazy\" width=\"48\" height=\"48\" class=\"image is-48x48 has-margin-bottom-small\" data-linktype=\"external\"/>⬇
 \t\t\t\t\t\t\t<h3 id=\"app-service-57\" class=\"font-size-h6 margin-none\"><a href=\"app-service/index.yml\" class=\"has-external-link-indicator stretched-link\" data-linktype=\"relative-path\">App Service</a ></h3>⬇
@@ -524,7 +524,7 @@
 \t\t\t\t\t\t\t\t<h3 class=\"font-size-h6 margin-none\">Azure Cognitive Search</h3>⬇
 \t\t\t\t\t\t\t</a>⬇
 \t\t\t\t</div>⬇
-\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Featured Blockchain Databases Internet of Things \">⬇
+\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Popular Blockchain Databases Internet of Things \">⬇
 \t\t\t\t\t\t<div class=\"is-hidden-mobile box position-relative margin-none is-full-height has-heavy-shadow-hover border-high-contrast-hover has-padding-large text-decoration-none\" aria-labelledby=\"azure-cosmos-db-54\">⬇
 \t\t\t\t\t\t\t\t<img src=\"https://static.docs.com/ui/media/product/azure/cosmos-db.svg\" alt=\"\" loading=\"lazy\" width=\"48\" height=\"48\" class=\"image is-48x48 has-margin-bottom-small\" data-linktype=\"external\"/>⬇
 \t\t\t\t\t\t\t<h3 id=\"azure-cosmos-db-54\" class=\"font-size-h6 margin-none\"><a href=\"cosmos-db/index.yml\" class=\"has-external-link-indicator stretched-link\" data-linktype=\"relative-path\">Azure Cosmos DB</a ></h3>⬇
@@ -744,7 +744,7 @@
 \t\t\t\t\t\t\t\t<h3 class=\"font-size-h6 margin-none\">Azure Front Door</h3>⬇
 \t\t\t\t\t\t\t</a>⬇
 \t\t\t\t</div>⬇
-\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Featured Compute Containers Internet of Things \">⬇
+\t\t\t\t<div class=\"column is-4-tablet is-3-desktop is-one-fifth-widescreen item-column\" data-categories=\"Popular Compute Containers Internet of Things \">⬇
 \t\t\t\t\t\t<div class=\"is-hidden-mobile box position-relative margin-none is-full-height has-heavy-shadow-hover border-high-contrast-hover has-padding-large text-decoration-none\" aria-la [...]

2021-12-10 10:59 UTC, opbld41 commented
<details><summary>⚠<a href='https://github.com/microsoftgraph/microsoft-graph-docs'>microsoft-graph-docs</a>(00:00:37.0836983)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/insights-customize-people-insights-privacy.raw.page.json" "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/insights-customize-people-insights-privacy.raw.page.json"
index 6f56293..c79f837 100644
--- "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/insights-customize-people-insights-privacy.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/insights-customize-people-insights-privacy.raw.page.json"
@@ -58,7 +58,7 @@
         }
       ],
       "update_at": "12/8/2021",
-      "updated_at_date_time": "2021-12-08T00:24:52.881Z"
+      "updated_at_date_time": "2021-12-08T00:24:56.198Z"
     },
     "author": "Anthona",
     "breadcrumb_path": "/graph/breadcrumb/toc.json",
@@ -98,7 +98,7 @@
     "toc_rel": "toc.json",
     "_op_ogTitle": "Customizing people insights privacy in Microsoft Graph - Microsoft Graph",
     "_op_og_attr_encoded_description": "Learn about how to customize people insights at the organization level using the Microsoft Graph API.",
-    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:52.881Z\"",
+    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:56.198Z\"",
     "_op_article_date_display": "12/8/2021",
     "_op_article_date_source": "git",
     "word_count": 336,
diff --git "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/known-issues.raw.page.json" "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/known-issues.raw.page.json"
index ddb845a..0926df2 100644
--- "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/known-issues.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/known-issues.raw.page.json"
@@ -533,7 +533,7 @@ Failure to read or update a photo, in this case, results in the following error:
         }
       ],
       "update_at": "12/8/2021",
-      "updated_at_date_time": "2021-12-08T00:24:52.881Z"
+      "updated_at_date_time": "2021-12-08T00:24:56.198Z"
     },
     "author": "MSGraphDocsvTeam",
     "breadcrumb_path": "/graph/breadcrumb/toc.json",
@@ -599,7 +599,7 @@ Failure to read or update a photo, in this case, results in the following error:
     "toc_rel": "toc.json",
     "_op_ogTitle": "Known issues with Microsoft Graph - Microsoft Graph",
     "_op_og_attr_encoded_description": "This article describes known issues with Microsoft Graph.",
-    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:52.881Z\"",
+    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:56.198Z\"",
     "_op_article_date_display": "12/8/2021",
     "_op_article_date_source": "git",
     "word_count": 3738,
diff --git "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/system-messages.raw.page.json" "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/system-messages.raw.page.json"
index 816c52a..773b24a 100644
--- "a/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\output/concepts/graph/system-messages.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.microsoft-graph-docs\\.temp/concepts/graph/system-messages.raw.page.json"
@@ -1490,7 +1490,7 @@ In this case, the <strong>messageType</strong> property is set to <code>systemEv
         }
       ],
       "update_at": "12/8/2021",
-      "updated_at_date_time": "2021-12-08T00:24:52.881Z"
+      "updated_at_date_time": "2021-12-08T00:24:56.198Z"
     },
     "author": "RamjotSingh",
     "breadcrumb_path": "/graph/breadcrumb/toc.json",
@@ -1529,7 +1529,7 @@ In this case, the <strong>messageType</strong> property is set to <code>systemEv
     "toc_rel": "toc.json",
     "_op_ogTitle": "Get system messages for Microsoft Teams using Microsoft Graph APIs - Microsoft Graph",
     "_op_og_attr_encoded_description": "Learn how Microsoft Teams generates system messages for events using Microsoft Graph APIs.",
-    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:52.881Z\"",
+    "_op_article_date_quotedISO8601": "\"2021-12-08T00:24:56.198Z\"",
     "_op_article_date_display": "12/8/2021",
     "_op_article_date_source": "git",
     "word_count": 2582,


```

</details>

2021-12-10 11:01 UTC, opbld41 commented
<details><summary>⚠<a href='https://github.com/MicrosoftDocs/windowsserverdocs-pr'>windowsserverdocs-pr</a>(00:00:11.4928664)</summary>

```diff
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/.publish.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/.publish.json"
index 1ece6a0..68c06a1 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/.publish.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/.publish.json"
@@ -103815,7 +103815,7 @@ This document contains frequently asked questions (FAQs) regarding forest recove
       "title": "Protect your Hyper-V Virtual Machines with Azure Site Recovery and Windows Admin Center | Microsoft Docs",
       "toc_rel": "../toc.json",
       "updated_at": "2021-12-03 12:30 AM",
-      "word_count": 1115
+      "word_count": 1118
     },
     {
       "url": "/windows-server/manage/windows-admin-center/azure/azure-update-management",
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.mta.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.mta.json"
index 3462dba..10caf92 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.mta.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.mta.json"
@@ -37,5 +37,5 @@
   "title": "Protect your Hyper-V Virtual Machines with Azure Site Recovery and Windows Admin Center | Microsoft Docs",
   "toc_rel": "../toc.json",
   "updated_at": "2021-12-03 12:30 AM",
-  "word_count": 1115
+  "word_count": 1118
 }
\ No newline at end of file
diff --git "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.raw.page.json" "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.raw.page.json"
index 665085d..4cc59b1 100644
--- "a/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\output/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.raw.page.json"
+++ "b/D:/docfx.TestData\\regression-test.windowsserverdocs-pr\\.temp/WindowsServerDocs/windows-server/manage/windows-admin-center/azure/azure-site-recovery.raw.page.json"
@@ -55,7 +55,7 @@
 </li>⬇
 <li><p>Select the VM you want to protect.</p>⬇
 </li>⬇
-<li><p>Select <strong>More</strong> &gt; <strong>Protect VM</strong>.</p>⬇
+<li><p>Select <strong>Manage</strong> &gt; <strong>Replicate using Azure Site Recovery</strong>.</p>⬇
 </li>⬇
 <li><p>Review the <a href=\"/en-us/azure/site-recovery/site-recovery-capacity-planner\" data-linktype=\"absolute-path\">capacity requirements for protecting the VM</a>.</p>⬇
 <p>If you want to use a premium storage account, <a href=\"/en-us/azure/storage/common/storage-premium-storage\" data-linktype=\"absolute-path\">create one in the Azure portal</a>. The <strong>Create New</strong> option provided in the Windows Admin Center pane creates a standard storage account.</p>⬇
@@ -180,13 +180,13 @@
     "_op_article_date_quotedISO8601": "\"2021-10-27T00:00:00.000Z\"",
     "_op_article_date_display": "10/27/2021",
     "_op_article_date_source": "ms.date",
-    "word_count": 1115,
+    "word_count": 1118,
     "_op_extendBreadcrumb": true,
     "_op_feedback_github_repo": "MicrosoftDocs/windowsserverdocs",
     "_op_feedback_product_url": "https://aka.ms/wacfeedback",
     "_op_feedback_system": "GitHub",
     "_op_rawTitle": "<h1 id=\"protect-your-hyper-v-virtual-machines-with-azure-site-recovery-and-windows-admin-center\">Protect your Hyper-V Virtual Machines with Azure Site Recovery and Windows Admin Center</h1>",
-    "_op_wordCount": 1115
+    "_op_wordCount": 1118
   },
   "pageMetadata": "<meta name=\"author\" content=\"IngridAtMicrosoft\" />\r⬇
 <meta name=\"breadcrumb_path\" content=\"/windows-server/breadcrumbs/toc.json\" />\r⬇
@@ -210,7 +210,7 @@
 <meta name=\"page_type\" content=\"conceptual\" />\r⬇
 <meta name=\"toc_rel\" content=\"../toc.json\" />\r⬇
 <meta name=\"pdf_url_template\" content=\"https://docs.microsoft.com/pdfstore/en-us/MSDN.WindowsServerDocs-pr/{branchName}{pdfName}\" />\r⬇
-<meta name=\"word_count\" content=\"1115\" />\r⬇
+<meta name=\"word_count\" content=\"1118\" />\r⬇
 ",
   "themesRelativePathToOutputRoot": "_themes/"
 }
\ No newline at end of file


```

</details>

2021-12-10 11:06 UTC, opbld41 commented
<details><summary>🧭<a href='https://github.com/MicrosoftDocs/azure-docs-pr'>dryrun.azure-docs-pr</a>(00:01:23.5748446 | exceed 80s)</summary>

```csharp
 29% | docfx!Microsoft.Docs.Build.ParallelUtility+<>c__DisplayClass2_0`1[System.__Canon].<ForEach>b__0(!0)
 25% | Microsoft.Docs.MarkdigExtensions!Microsoft.Docs.MarkdigExtensions.ResolveLinkExtension.UpdateLinks(class Markdig.Syntax.MarkdownObject)
 24% | docfx!Microsoft.Docs.Build.DocsetBuilder+<>c__DisplayClass42_1.<Build>b__16(class Microsoft.Docs.Build.FilePath)
 22% | docfx!Microsoft.Docs.Build.PageBuilder.Build(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 21% | docfx!Microsoft.Docs.Build.PageBuilder.LoadMarkdown(class Microsoft.Docs.Build.ErrorBuilder,class Microsoft.Docs.Build.FilePath)
 16% | docfx!Microsoft.Docs.Build.MarkdownEngine.ToHtml(class Microsoft.Docs.Build.ErrorBuilder,class System.String,class Microsoft.Docs.Build.SourceInfo,value class Microsoft.Docs.Build.MarkdownPipelineType,class Microsoft.Docs.Build.ConceptualModel,bool)
 15% | Markdig!Markdig.Markdown.ToHtml(class System.String,class Markdig.MarkdownPipeline)
 12% | Markdig!Markdig.Parsers.MarkdownParser.Parse()
  8% | Markdig!Markdig.Renderers.RendererBase.Write(class Markdig.Syntax.MarkdownObject)
  8% | docfx!Microsoft.Docs.Build.MarkdigUtility.<Replace>g__ReplaceCore|7_0(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,class Markdig.Syntax.MarkdownObject>)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass6_0.<CreateCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Docfx+<>c__DisplayClass4_0.<BuildCommand>b__0(class Microsoft.Docs.Build.CommandLineOptions)
  6% | docfx!Microsoft.Docs.Build.Builder.Run(class Microsoft.Docs.Build.CommandLineOptions,class Microsoft.Docs.Build.Package)
  6% | docfx!Microsoft.Docs.Build.Builder.Build(class Microsoft.Docs.Build.ErrorBuilder,class System.IProgress`1<class System.String>,class System.String[])
  5% | docfx!Microsoft.Docs.Build.MarkdigUtility.Visit(class Markdig.Syntax.MarkdownObject,class System.Func`2<class Markdig.Syntax.MarkdownObject,bool>)
  5% | docfx!Microsoft.Docs.Build.LinkResolver.ResolveLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode)
  5% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetLink(class Microsoft.Docs.Build.LinkInfo)
  4% | docfx!Microsoft.Docs.Build.Watcher.Write(class System.Action)
  4% | Microsoft.Graph.Core!Microsoft.Graph.RedirectHandler+<SendAsync>d__6.MoveNext()
  4% | Microsoft.Graph.Core!Microsoft.Graph.RetryHandler+<SendAsync>d__9.MoveNext()
  4% | Markdig!Markdig.Renderers.RendererBase.WriteChildren(class Markdig.Syntax.ContainerBlock)
  4% | docfx!Microsoft.Docs.Build.Builder+<>c__DisplayClass8_0.<Build>b__0(class Microsoft.Docs.Build.DocsetBuilder)
  3% | docfx!Microsoft.Docs.Build.LinkResolver.TryResolveAbsoluteLink(value class Microsoft.Docs.Build.SourceInfo`1<class System.String>,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Build.FilePath,class Microsoft.Docs.Validation.LinkNode)
  3% | docfx!Microsoft.Docs.Build.DocsetBuilder.Build(class System.String[])
  3% | docfx!Microsoft.Docs.Build.MarkdownEngine.GetImageLink(class System.String,class Markdig.Syntax.MarkdownObject,class System.String,class System.String)
  3% | docfx!Microsoft.Docs.Build.ParallelUtility.ForEach(class Microsoft.Docs.Build.LogScope,class Microsoft.Docs.Build.ErrorBuilder,class System.Collections.Generic.IEnumerable`1<!!0>,class System.Action`1<!!0>)
  3% | docfx!Microsoft.Docs.Build.Watch`1[System.__Canon].get_Value()
  3% | docfx!Microsoft.Docs.Build.ErrorBuilder.AddRange(class System.Collections.Generic.IEnumerable`1<class Microsoft.Docs.Build.Error>)
  3% | Microsoft.Graph.Core!Microsoft.Graph.CompressionHandler+<SendAsync>d__2.MoveNext()
  3% | docfx!Microsoft.Docs.Build.JsonSchemaValidator.Validate(class Microsoft.Docs.Build.JsonSchema,class System.String,class Newtonsoft.Json.Linq.JToken,class System.Collections.Generic.List`1<class Microsoft.Docs.Build.Error>,class Microsoft.Docs.Build.JsonSchemaMap)

```

</details>

2021-12-14 07:49 UTC, fkpwolf commented
close this PR and replace with `propertyPath` approach.

2021-12-14 07:49 UTC, closed without merging