Get GitHub access token from build api
dotnet/docfx pull request #8164
Opened 2022-09-02 07:10 UTC by irushx

2022-09-02 08:07 UTC, 928PJY commented
/azp run

2022-09-02 08:10 UTC, 928PJY commented
/azp rim

2022-09-02 08:11 UTC, 928PJY commented
/azp run

2022-09-13 05:10 UTC, 928PJY approved these changes
:shipit:

2022-09-14 05:43 UTC, 928PJY commented
/azp run

2022-09-14 05:48 UTC, 928PJY commented
/azp run

2022-09-16 07:44 UTC, AngryBerryMS commented
/azp run

2022-09-16 07:54 UTC, herohua requested changes
temporarily holding the approval

2022-09-19 06:35 UTC, herohua approved these changes
You can start testing on PubDev now.

2022-09-19 06:35 UTC, herohua commented
/azp run

2022-09-27 07:46 UTC, 928PJY commented on docs/specs/git.yml
> -    secrets:
We should cover the two cases in spec test:
- token from secrets
- token from API call.

2022-09-27 08:37 UTC, 928PJY approved these changes

2022-09-28 01:20 UTC, merged